# Server Configuration
server.port=8080

# MongoDB Configuration
# spring.data.mongodb.uri=mongodb://localhost:27017/live-auction
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI}

# CORS Configuration
spring.web.cors.allowed-origins=*

# Logging
logging.level.com.auction=DEBUG

